### ISSUE TITLE
Change attributes order in left panel

### ISSUE THREAD

**Issue by AxelRD** [raphv/gexf-js#31]
Hi,

As I'm not very gifted at using JS I'd like to know if there is a tweak to set the order of the attributes displayed in the left panel.
I identified the part of the code that set this array (line 239 of gexfjs) but i'm unable to change the order of the elements. Any ideas ?

Thanks for this great script !

**Comment by raphv** [comment]
Hi Axel,
Please checkout the latest version of the script. I've added alphabetcal sorting of attributes. If you want to change the way these attributes are sorted, modify the code around line 639.

Cheers,
R.
