### ISSUE TITLE
Graphs not loading in Firefox

### ISSUE THREAD

**Issue by angusveitch** [raphv/gexf-js#47]
I'm just wondering if there have been recent changes to Firefox that have stopped local gexf-js pages from loading? I've tried on two different computers now, and all graphs (including the packaged examples) now just come up blank on Firefox.

**Comment by raphv** [comment]
Hello Angus,
I've searched for the issue and I confirm that Firefox has updated its security model as of version 68 (released July 2019).
There is a workaround which is to go to ### about:config and set s**ecurity.fileuri.strict_origin_policy** to **false**
I have updated the documentation accordingly.
